"""Add facility_id and created_by to User model

Revision ID: 3551cc467a91
Revises: 05f69b2b7ab0
Create Date: 2025-03-03 12:29:10.143582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3551cc467a91'
down_revision = '05f69b2b7ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clinical_cases', schema=None) as batch_op:
        batch_op.alter_column('symptoms',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_constraint('clinical_cases_reporter_id_fkey', type_='foreignkey')
        batch_op.drop_column('reporter_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.Integer(), nullable=True))
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'RESEARCHER', 'GUEST', 'facility_manager', 'FACILITY_MANAGER', name='userrole'),
               nullable=False)
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('ADMIN', 'RESEARCHER', 'GUEST', 'facility_manager', 'FACILITY_MANAGER', name='userrole'),
               nullable=True)
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('clinical_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('clinical_cases_reporter_id_fkey', 'users', ['reporter_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('symptoms',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))

    op.drop_table('facilities')
    # ### end Alembic commands ###
