"""update_subscription_backref

Revision ID: 3e65e2fedffd
Revises: 614bdc7d6e32
Create Date: 2025-03-05 22:20:20.849551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e65e2fedffd'
down_revision = '614bdc7d6e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_racks',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('max_racks',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
