"""Add subscription relationships

Revision ID: 498bb50d0e9f
Revises: 3e65e2fedffd
Create Date: 2025-03-07 15:12:43.598293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '498bb50d0e9f'
down_revision = '3e65e2fedffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_tiers', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint('subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('original_plan_end_date')
        batch_op.drop_column('user_id')
        batch_op.drop_column('original_plan_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_plan_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_plan_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('subscriptions_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('subscription_tiers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
