"""Add user_id to subscriptions table

Revision ID: 555bec31e454
Revises: 498bb50d0e9f
Create Date: 2025-03-10 12:57:07.929461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555bec31e454'
down_revision = '498bb50d0e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
