"""empty message

Revision ID: 614bdc7d6e32
Revises: 3551cc467a91
Create Date: 2025-03-05 22:14:33.989059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '614bdc7d6e32'
down_revision = '3551cc467a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_tiers', schema=None) as batch_op:
        batch_op.drop_constraint('subscription_tiers_subscription_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subscriptions', ['subscription_id'], ['id'])

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('facility_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('max_users',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('facility_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('subscription_tiers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscription_tiers_subscription_id_fkey', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
